# Generated by Django 5.2.17 on 2026-09-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='ended_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
