# Generated by Django 5.2.17 on 2026-09-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
